#!/usr/bin/python3

# import time
# start_time = time.time()

import sys

prime_base = [2, 3, 5, 6, 7, 11, 13, 17, 19]


def text2num(text):
    if ',' not in text and '.' not in text:
        return int(text)
        # return int(text)
    elif ',' not in text and '.' in text:
        return float(text)
    elif ',' in text and '.' not in text:
        number = int(''.join(text.split(',')))
        return number
    elif ',' in text and '.' in text:
        number = float(''.join(text.split(',')))
        return number


def sqrt(num):
    return num ** .5


def prime_factor2(num):
    sqrt_base = int(sqrt(num)) + 1
    j = int(sqrt(num)) + 1
    while num % j != 0:
        j -= 1
    return j


def prime_factor1(num):
    for i in prime_base:
        if num % i == 0:
            print(f"{num}={int(num / i)}*{i}")
            return
    j = prime_factor2(num)
    print(f"{num}={int(num / j)}*{j}")


if len(sys.argv) > 1:
    with open(sys.argv[1], 'r') as f:
        lines = f.readlines()
numbers = list(map(text2num, lines))
factorized = list(map(prime_factor1, numbers))

# print(f"{time.time() - start_time}")
